### ISSUE TITLE
Hyper-parameters of the GBM classifier used in the paper

### ISSUE THREAD

**Issue by mjuarezm** [zykls/folktables#11]
Hi,

First, thanks for your work. `folktables` is proving extremely useful for my research.

**I'm trying to reproduce the results in the paper and I would like to know the hyper-parameters that you used to train the GBM.**

Thank you!

**Comment by millerjohnp** [comment]
Hi, The hyperparameters for the experiments we ran are detailed in the different Appendices of [our paper](https://arxiv.org/abs/2108.04884), specifically sections A.2, B.7, C, and D each correspond to one experiment in the main text.

**Comment by mjuarezm** [comment]
I'm sorry, I had missed that. Thanks for the clarification!
