### ISSUE TITLE
The semantic meaning of features in ACS dataset

### ISSUE THREAD

**Issue by peizhaoli05** [zykls/folktables#13]
Hi,

Thanks for collecting the datasets for algorithmic fairness!

I looked into the ACS datasets and found you manually defined the used features for each predictive task. May I ask where can I find the semantic meaning for each feature? e.g., COW, SCHL. Are they numerical or categorical?

Thank you!

**Comment by britneyting** [comment]
Hi, I'm not one of the maintainers of folktables, but I found the original descriptions for each feature on the census website [here](https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2014-2018.pdf).  Hope this helps!

**Comment by francesding** [comment]
Thanks for the question! As @britneyting mentioned, the Census website lists the meanings and possible values for each feature. The link above is for the 2014-2018 dataset, and other years' documentation can be found [here](https://www.census.gov/programs-surveys/acs/microdata/documentation.html).
