### ISSUE TITLE
Feature request: Return the BasicProblem as translated dataframes

### ISSUE THREAD

**Issue by jenno-verdonck** [zykls/folktables#17]
In the current version of folktables it is possible to return the defined problems as numpy array's. I propose a nice to have feature returning the filtered and processed data as pandas dataframes. This would allow easier formatting and outputting of the problems to csv files for further use in other tools and languages.

A possible extension to this would be to automatically translate the numerical categorical values using the available data dictionaries on the census website. This would make reasoning and analysis of the columns easier.

**Comment by mrtzh** [comment]
This has now been implemented. See PR [#21](https://github.com/zykls/folktables/pull/21).
