### ISSUE TITLE
time horizon and survey year

### ISSUE THREAD

**Issue by YiheWang** [zykls/folktables#18]
Hi, I wonder if horizon = '5-Year' means it will load all the samples from 2014-to 2018? In this case, is it meanless to specify survey_year?

For example, are there any differences between [survey_year='2018', horizon='5-Year'] and [survey_year='2017', horizon='5-Year'] ? 

Thanks in advance for your help!

**Comment by mrtzh** [comment]
Yes, there is a difference. The Census Bureau releases ACS 1-year and 5-year PUMS files each year. So, in 2018 the 5-year file combines data from 2014-2018. In 2017, the 5-year file includes data from 2013-2017.
