### ISSUE TITLE
Is there a feature that indicates which state a sample comes from?

### ISSUE THREAD

**Issue by YiheWang** [zykls/folktables#19]
Hi, I wonder if there is a feature that shows which state an instance comes from?

For example, I download both TX and CA data samples. I want to figure out an instance that comes from CA or TX.

Thanks in advance for your help!

**Comment by mrtzh** [comment]
Yes, it's in the ACS data, you can load with `load_acs.py`. 

The column is called 'ST' in the data frame. See the Census documentation: https://www2.census.gov/programs-surveys/acs/tech_docs/pums/data_dict/PUMS_Data_Dictionary_2016-2020.pdf

The column is not included in the prediction tasks folktables exposes by default.
