### ISSUE TITLE
Replace `sklearn` with `scikit-learn`

### ISSUE THREAD

**Issue by jansim** [zykls/folktables#32]
Hello, thanks for building this lovely package!

Since `sklearn` is being deprecated as a package name in favor of `scikit-learn`, this leads to errors when trying to install the package during certain times (as part of their brownout strategy). These errors will become more common as the times of the brownout are increased.

More info on this issue here: https://pypi.org/project/sklearn/

So far I've only noticed the setup.py actually referencing `sklearn`, so the solution here might be as easy as replacing `sklearn` in the setup.py with `scikit-learn`. All import calls should remain unaffected.

**Comment by AndreFCruz** [comment]
FYI, just had an install error based on sklearn being deprecated:
<img width="719" alt="Screenshot 2023-02-01 at 14 11 49" src="https://user-images.githubusercontent.com/13498941/216052467-b1c6333a-fc5d-4e54-81fe-5c4bdead255d.png">

Using python 3.9.16 on an Intel mac.
